@startuml Последовательный метод Зейделя
start
title Последовательный метод Зейделя

:Инициализация матрицы A и вектора b;
:Инициализация начального вектора решения x нулями;

repeat
    :Сохранить текущее решение prev_x = x;
    :Для каждой строки i в матрице A выполняем следующие шаги:;
    repeat
        :Вычислить сумму (b[i] - Σ(A[i][j] * x[j])) / A[i][i];
        :Обновить x[i];
    repeat while (i < размер матрицы)

    :Вычислить ошибку как сумму |x[i] - prev_x[i]|;
repeat while (ошибка > TOLERANCE или итерации < MAX_ITER)

:Возврат x как решение;
stop
@enduml
