@startuml Gauss-Jordan Parallel Method
start
:Initialize matrix A and vector b;
:MPI_Init;
:MPI_Comm_rank -> rank;
:MPI_Comm_size -> size;
:For i = 0 to n-1;
  if (rank == i % size) then (yes)
    :Pivot = A[i][i];
    :Normalize row i;
    :For j = 0 to n-1;
      if (i != j) then (yes)
        :Eliminate element A[j][i];
      endif
  endif
  :MPI_Barrier;
:Return solution vector b;
:MPI_Finalize;
stop
@enduml
