@startuml Параллельный алгоритм сортировки выбором
start
:Инициализация MPI;
:Получение массива данных;
:Установка n = размер массива;
:Разделение массива на части (MPI_Scatter);

fork
  :Локальная сортировка в каждом потоке;
fork again
  :Поиск локального минимума в каждом потоке;
end fork

repeat
  if (Поток 0?) then (да)
    :Сбор локальных минимумов от всех потоков (MPI_Recv);
    :Определение глобального минимума;
    :Рассылка номера потока с глобальным минимумом (MPI_Bcast);
  else (нет)
    :Ожидание номера потока с глобальным минимумом (MPI_Bcast);
  endif

  if (Этот поток содержит глобальный минимум?) then (да)
    :Обновление локального массива (новый минимум);
  endif

  :Синхронизация всех потоков (MPI_Barrier);
repeat while (шаг < n)

:Сбор всех данных в потоке 0 (MPI_Gather);
:Конец MPI;
stop
@enduml
